import { 
  FaUser, FaGraduationCap, FaSchool, FaUniversity, FaBook, FaBookOpen, 
  FaUserGraduate, FaChalkboardTeacher, FaAtom, FaFlask, FaCalculator, 
  FaMicroscope, FaDna, FaLightbulb, FaSatellite, FaRocket, FaWind, 
  FaSolarPanel, FaStethoscope, FaHeartbeat, FaPills, FaClinicMedical, 
  FaSyringe, FaBone, FaEye, FaTeeth, FaAllergies, FaWeightHanging, 
  FaDumbbell, FaBasketballBall, FaTableTennis, FaSwimmingPool, FaRunning, 
  FaBiking, FaFootballBall, FaCarrot, FaAppleAlt, FaHamburger, FaPizzaSlice, 
  FaIceCream, FaMusic, FaPaintBrush, FaPalette, FaCamera, FaCode, FaRobot, 
  FaGlobe, FaHistory, FaLanguage, FaBrain, FaChess, FaSeedling, FaChartLine 
} from 'react-icons/fa';

export const getIconByName = (iconName: string) => {
  const iconsMap: Record<string, JSX.Element> = {
    'user': <FaUser />,
    'graduation': <FaGraduationCap />,
    'school': <FaSchool />,
    'university': <FaUniversity />,
    'book': <FaBook />,
    'open-book': <FaBookOpen />,
    'graduate': <FaUserGraduate />,
    'teacher': <FaChalkboardTeacher />,
    'atom': <FaAtom />,
    'flask': <FaFlask />,
    'calculator': <FaCalculator />,
    'microscope': <FaMicroscope />,
    'dna': <FaDna />,
    'lightbulb': <FaLightbulb />,
    'satellite': <FaSatellite />,
    'rocket': <FaRocket />,
    'wind': <FaWind />,
    'solar-panel': <FaSolarPanel />,
    'stethoscope': <FaStethoscope />,
    'heartbeat': <FaHeartbeat />,
    'pills': <FaPills />,
    'clinic': <FaClinicMedical />,
    'syringe': <FaSyringe />,
    'bone': <FaBone />,
    'eye': <FaEye />,
    'teeth': <FaTeeth />,
    'allergies': <FaAllergies />,
    'weight': <FaWeightHanging />,
    'dumbbell': <FaDumbbell />,
    'basketball': <FaBasketballBall />,
    'table-tennis': <FaTableTennis />,
    'swimming': <FaSwimmingPool />,
    'running': <FaRunning />,
    'biking': <FaBiking />,
    'football': <FaFootballBall />,
    'carrot': <FaCarrot />,
    'apple': <FaAppleAlt />,
    'hamburger': <FaHamburger />,
    'pizza': <FaPizzaSlice />,
    'ice-cream': <FaIceCream />,
    'music': <FaMusic />,
    'paint': <FaPaintBrush />,
    'palette': <FaPalette />,
    'camera': <FaCamera />,
    'code': <FaCode />,
    'robot': <FaRobot />,
    'globe': <FaGlobe />,
    'history': <FaHistory />,
    'language': <FaLanguage />,
    'brain': <FaBrain />,
    'chess': <FaChess />,
    'seedling': <FaSeedling />,
    'chart': <FaChartLine />
  };

  return iconsMap[iconName] || <FaUserGraduate />;
};